version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: node worker/worker.js
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    

  redis:
    image: redis
    ports:
      - "5002:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: